services:

  mariadb:
    image: mariadb:lts
    container_name: sftshop_mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - sftshopdbdata:/var/lib/mysql

  adminer:
    image: adminer
    container_name: sftshop_adminer
    restart: always
    ports:
      - 8006:8080

volumes:
  sftshopdbdata:
